export const FooterLinks = [
  "FAQ",
  "Investor Relations",
  "Ways to Watch",
  "Help Center",
  "Account",
  "Media Center",
  "Jobs",
  "Redeem Gift Cards",
  "Buy Gift Cards",
  "Terms of Use",
  "Privacy",
  "Cookie Preferences",
  "Corporate Information",
  "Contact Us",
  "Speed Test",
  "Legal",
  "Notices",
  "Only on Netflix",
]

export const FooterHeading = "Questions? Call 1-844-505-2993"

// export const FooterActions = [
//   "explore what's on",
//   "movies",
//   "tv shows",
//   "originals",
//   "free episodes",
// ]

export const CopyrightText =
  "© 2022 WarnerMedia Direct, LLC. All Rights Reserved. HBO Max™ is used under license."

export const trayPics1 = [
  "tile_15.jpg",
  "tile_16.jpg",
  "tile_17.jpg",
  "tile_18.jpg",
  "tile_19.jpg",
  "tile_20.jpg",
  "tile_21.jpg",
  "tile_22.jpg",
  "tile_23.jpg",
  "tile_24.jpg",
  "tile_25.jpg",
  "tile_26.jpg",
  "tile_27.jpg",
  "tile_28.jpg",
  "tile_15.jpg",
  "tile_16.jpg",
  "tile_17.jpg",
  "tile_18.jpg",
  "tile_19.jpg",
  "tile_20.jpg",
  "tile_21.jpg",
  "tile_22.jpg",
  "tile_23.jpg",
  "tile_24.jpg",
  "tile_25.jpg",
  "tile_26.jpg",
  "tile_27.jpg",
  "tile_28.jpg",
  "tile_15.jpg",
  "tile_16.jpg",
  "tile_17.jpg",
  "tile_18.jpg",
  "tile_19.jpg",
  "tile_20.jpg",
  "tile_21.jpg",
  "tile_22.jpg",
  "tile_23.jpg",
  "tile_24.jpg",
  "tile_25.jpg",
  "tile_26.jpg",
  "tile_27.jpg",
  "tile_28.jpg",
]
export const trayPics2 = [
  "tile_14.jpg",
  "tile_13.jpg",
  "tile_12.jpg",
  "tile_11.jpg",
  "tile_10.jpg",
  "tile_9.jpg",
  "tile_8.jpg",
  "tile_7.jpg",
  "tile_6.jpg",
  "tile_5.jpg",
  "tile_4.jpg",
  "tile_3.jpg",
  "tile_2.jpg",
  "tile_1.jpg",
  "tile_0.jpg",
  "tile_14.jpg",
  "tile_13.jpg",
  "tile_12.jpg",
  "tile_11.jpg",
  "tile_10.jpg",
  "tile_9.jpg",
  "tile_8.jpg",
  "tile_7.jpg",
  "tile_6.jpg",
  "tile_5.jpg",
  "tile_4.jpg",
  "tile_3.jpg",
  "tile_2.jpg",
  "tile_1.jpg",
  "tile_0.jpg",
  "tile_14.jpg",
  "tile_13.jpg",
  "tile_12.jpg",
  "tile_11.jpg",
  "tile_10.jpg",
  "tile_9.jpg",
  "tile_8.jpg",
  "tile_7.jpg",
  "tile_6.jpg",
  "tile_5.jpg",
  "tile_4.jpg",
  "tile_3.jpg",
  "tile_2.jpg",
  "tile_1.jpg",
  "tile_0.jpg",
]
