export const FooterLinks = [
  "Privacy",
  "Do Not Sell My Personal Information",
  "Terms of Use",
  "Ad Choices",
  "Help",
  "Join the Team",
  "Press Releases",
  "Company",
  "Press Contacts",
  "HBO Max Advertising",
  "Affiliate Marketing Program",
];

export const FooterActions = [
  "explore what's on",
  "movies",
  "tv shows",
  "originals",
  "free episodes",
];

export const CopyrightText =
  "© 2022 WarnerMedia Direct, LLC. All Rights Reserved. HBO Max™ is used under license.";

export const trayPics1 = [
  "/images/tiles/tile_15.jpg",
  "/images/tiles/tile_16.jpg",
  "/images/tiles/tile_17.jpg",
  "/images/tiles/tile_18.jpg",
  "/images/tiles/tile_19.jpg",
  "/images/tiles/tile_20.jpg",
  "/images/tiles/tile_21.jpg",
  "/images/tiles/tile_22.jpg",
  "/images/tiles/tile_23.jpg",
  "/images/tiles/tile_24.jpg",
  "/images/tiles/tile_25.jpg",
  "/images/tiles/tile_26.jpg",
  "/images/tiles/tile_27.jpg",
  "/images/tiles/tile_28.jpg",
  "/images/tiles/tile_15.jpg",
  "/images/tiles/tile_16.jpg",
  "/images/tiles/tile_17.jpg",
  "/images/tiles/tile_18.jpg",
  "/images/tiles/tile_19.jpg",
  "/images/tiles/tile_20.jpg",
  "/images/tiles/tile_21.jpg",
  "/images/tiles/tile_22.jpg",
  "/images/tiles/tile_23.jpg",
  "/images/tiles/tile_24.jpg",
  "/images/tiles/tile_25.jpg",
  "/images/tiles/tile_26.jpg",
  "/images/tiles/tile_27.jpg",
  "/images/tiles/tile_28.jpg",
  "/images/tiles/tile_15.jpg",
  "/images/tiles/tile_16.jpg",
  "/images/tiles/tile_17.jpg",
  "/images/tiles/tile_18.jpg",
  "/images/tiles/tile_19.jpg",
  "/images/tiles/tile_20.jpg",
  "/images/tiles/tile_21.jpg",
  "/images/tiles/tile_22.jpg",
  "/images/tiles/tile_23.jpg",
  "/images/tiles/tile_24.jpg",
  "/images/tiles/tile_25.jpg",
  "/images/tiles/tile_26.jpg",
  "/images/tiles/tile_27.jpg",
  "/images/tiles/tile_28.jpg",
];
export const trayPics2 = [
  "/images/tiles/tile_14.jpg",
  "/images/tiles/tile_13.jpg",
  "/images/tiles/tile_12.jpg",
  "/images/tiles/tile_11.jpg",
  "/images/tiles/tile_10.jpg",
  "/images/tiles/tile_9.jpg",
  "/images/tiles/tile_8.jpg",
  "/images/tiles/tile_7.jpg",
  "/images/tiles/tile_6.jpg",
  "/images/tiles/tile_5.jpg",
  "/images/tiles/tile_4.jpg",
  "/images/tiles/tile_3.jpg",
  "/images/tiles/tile_2.jpg",
  "/images/tiles/tile_1.jpg",
  "/images/tiles/tile_0.jpg",
  "/images/tiles/tile_14.jpg",
  "/images/tiles/tile_13.jpg",
  "/images/tiles/tile_12.jpg",
  "/images/tiles/tile_11.jpg",
  "/images/tiles/tile_10.jpg",
  "/images/tiles/tile_9.jpg",
  "/images/tiles/tile_8.jpg",
  "/images/tiles/tile_7.jpg",
  "/images/tiles/tile_6.jpg",
  "/images/tiles/tile_5.jpg",
  "/images/tiles/tile_4.jpg",
  "/images/tiles/tile_3.jpg",
  "/images/tiles/tile_2.jpg",
  "/images/tiles/tile_1.jpg",
  "/images/tiles/tile_0.jpg",
  "/images/tiles/tile_14.jpg",
  "/images/tiles/tile_13.jpg",
  "/images/tiles/tile_12.jpg",
  "/images/tiles/tile_11.jpg",
  "/images/tiles/tile_10.jpg",
  "/images/tiles/tile_9.jpg",
  "/images/tiles/tile_8.jpg",
  "/images/tiles/tile_7.jpg",
  "/images/tiles/tile_6.jpg",
  "/images/tiles/tile_5.jpg",
  "/images/tiles/tile_4.jpg",
  "/images/tiles/tile_3.jpg",
  "/images/tiles/tile_2.jpg",
  "/images/tiles/tile_1.jpg",
  "/images/tiles/tile_0.jpg",
];
